### ISSUE TITLE
cuDNN error, running test.py

### ISSUE THREAD

**Issue by Xiaoyao-Li** [MCG-NKU/E2FGVI#59]
Hello there, nice work!

I was trying to reproduce the demo results, running test.py demo provided in your repo, and I occurred cuDNN error:
```
cuDNN error: CUDNN_STATUS_EXECUTION_FAILED
  File "/home/puhao/dev/MAH/DataPreprocess/E2FGVI/model/modules/flow_comp.py", line 382, in flow_warp
    align_corners=align_corners)
  File "/home/puhao/dev/MAH/DataPreprocess/E2FGVI/model/modules/feat_prop.py", line 111, in forward
    cond_n1 = flow_warp(feat_prop, flow_n1.permute(0, 2, 3, 1))
  File "/home/puhao/dev/MAH/DataPreprocess/E2FGVI/model/e2fgvi.py", line 250, in forward
    pred_flows[1])
  File "/home/puhao/dev/MAH/DataPreprocess/E2FGVI/test.py", line 168, in main_worker
    pred_imgs, _ = model(masked_imgs, len(neighbor_ids))
  File "/home/puhao/dev/MAH/DataPreprocess/E2FGVI/test.py", line 227, in <module>
    main_worker()
RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED
```
at `line 382` in flow_comp.py.

I installed the environment with conda, following the instruction in your README, and I also found that it **only** occurred when i try to run it on **cuda version**.

---test platform---
system: Ubuntu 20.04.5 LTS
gpu: Nvidia 3090Ti
---test platform---

---env---
**Name                    Version                   Build  Channel**
cudatoolkit               10.1.243             h6bb024c_0    anaconda
cudnn                     7.6.5                cuda10.1_0    anaconda
mmcv-full                 1.7.1                    pypi_0    pypi
---env---

Do you know why, and it will be very helpful if you can give me some suggestion.

**Comment by Xiaoyao-Li** [comment]
Hi, I have solved this problem by change cuda version. the cuda version for pytorch, cudnn, cudatoolkit specified in `environment.yml` is not general for all platform. But it can simplified be re-install with a proper version.

**Comment by smandava98** [comment]
what cuda version did you use? Am having same issue
